version: "3.8"

services:
  spark-master:
    build: .
    container_name: gr2-spark-master
    hostname: spark-master
    ports:
      - "8080:8080"   # Spark UI
      - "7077:7077"   # Spark master port
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark/jobs:/app/jobs
    networks:
      - spark-net

  spark-worker-1:
    build: .
    container_name: gr2-spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-net

  spark-worker-2:
    build: .
    container_name: gr2-spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-net
  

networks:
  spark-net:
    driver: bridge