services:
  spark-master:
    build: .
    container_name: gr2-spark-master
    hostname: gr2-spark-master
    ports:
      - "8080:8080"   # Spark Master UI
      - "7077:7077"   # Spark Master port
      - "8000:8000"   # FastAPI
    environment:
      SPARK_MODE: master
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./spark/jobs:/app/jobs
      - ./main.py:/root/main.py
      - ./spark-defaults.conf:/usr/local/gr2/spark/conf/spark-defaults.conf:ro
    networks:
      - spark-net

  spark-worker-1:
    build: .
    container_name: gr2-spark-worker-1
    hostname: gr2-spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER: spark://gr2-spark-master:7077
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./spark-defaults.conf:/usr/local/gr2/spark/conf/spark-defaults.conf:ro
    networks:
      - spark-net

  spark-worker-2:
    build: .
    container_name: gr2-spark-worker-2
    hostname: gr2-spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER: spark://gr2-spark-master:7077
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./spark-defaults.conf:/usr/local/gr2/spark/conf/spark-defaults.conf:ro
    networks:
      - spark-net

  postgres:
    image: postgres:14
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  airflow:
    build: ./airflow
    container_name: airflow
    restart: always
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - spark-net

  trino:
    image: trinodb/trino:477
    container_name: trino
    restart: always
    ports:
      - "8090:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./trino:/etc/trino
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge

volumes:
  postgres_data: